all: Surv_SpaceAgeTime_ByType_withUnknownType.dll

Surv_SpaceAgeTime_ByType_withUnknownType.dll: Surv_SpaceAgeTime_ByType_withUnknownType.cpp
	Rscript --vanilla -e "TMB::compile('Surv_SpaceAgeTime_ByType_withUnknownType.cpp')"

clean:
	rm -rf *o
